export default {
  white: '#fff',
  black: '#000',
  backgroundGrey50: 'rgba(52,52,52,0.5)',
  grey: '#EAEAEA',
  textGrey: '#707070',
  errorBackground: '#f8d7da',
  transparent: 'transparent',
  primary: '#0C2F58',
  background: '#efefef',
  secondary: '#AF7650',
  success: 'green',
  danger: 'red',
  warning: 'orange',
  gold: '#A38C53',
};
