export { default as SignInForm } from './sign-in/sign-in.form';
// export { default as UserInfoForm } from './user-info/user-info.form';
export { default as MobileNumberForm } from './mobile-number/mobile-number.form';
export { default as MembershipCardForm } from './membership-card/membership-card.form';
export { default as NumericalInputForm } from './numerical-input/numerical-input.form';
export { default as SetPasswordForm } from './set-password/set-password.form';
export { default as CreditCardForm } from './credit-card/credit-card.form';
export { default as BankAccountForm } from './bank-account/bank-account.form';
export { default as UploadDocumentForm } from './bank-account/upload-document.form';
export { default as HealthSurveyForm } from './health-survey/health-survey.form';
export { default as TopUpForm } from './top-up/top-up.form';
export { default as PayOutForm } from './pay-out/pay-out.form';
export { default as ProfileForm } from './profile-form/profile.form';
export { default as UploadProfileDocumentsForm } from './profile-form/upload-profile-documents.form';
export { default as RegisterEmailForm } from './register-email/register-email.form';
export { default as JackpotListForm } from './jackpot-list/jackpot-list.form';
export { default as PredictionsForm } from './hot-slots-predictions/predictions.form';
export { default as QrInputForm } from './qr-input/qr-input.form';
